### ISSUE TITLE
iRacing Screen stays black

### ISSUE THREAD

**Issue by arajkov** [Jabbah/OpenXR-Layer-OBSMirror#1]
What a great addition with an OpenXR Plugin for OBS! Thanks for picking this up.
Generally plugin is found and I can crop the image - but in iRacing the projection screen stays black.
Is this not supported or do you need to adapt for every title on its own ?

**Comment by Jabbah** [comment]
I don't have iRacing so haven't tested it with that yet. Have you tried the plugin with anything else to check it is working? 

Could you also post the log file from %LocalAppData% ? I think it's just in that dir and called OpenXR-layer-OBSMirror.log or similar.

**Comment by arajkov** [comment]
Nothing unusual in here ... tested MFS2020 and I got an image. Dont know whats happening with iRacing. Screen stays black.

[XR_APILAYER_NOVENDOR_OBSMirror.log](https://github.com/Jabbah/OpenXR-Layer-OBSMirror/files/10299605/XR_APILAYER_NOVENDOR_OBSMirror.log)

**Comment by Jabbah** [comment]
Thanks for the log, looks like it is doing something different to other
games so far but shouldn't be a huge issue. Will take a look next week.

**Comment by arajkov** [comment]
That would be Great! Thanks for your effort.

**Comment by Jabbah** [comment]
Try this dll. Just replace the dll in the install location.

[XR_APILAYER_NOVENDOR_OBSMirror.zip](https://github.com/Jabbah/OpenXR-Layer-OBSMirror/files/10304777/XR_APILAYER_NOVENDOR_OBSMirror.zip)

**Comment by arajkov** [comment]
Great, thanks Jabbah! Got it running with this DLL - but somehow my renderer times are way higher when running this injection. Need to figure out where this behavior comes from. Current logfile attached - there is something going on with a DXGI Texture. Maby this has something to do with it.

[XR_APILAYER_NOVENDOR_OBSMirror.log](https://github.com/Jabbah/OpenXR-Layer-OBSMirror/files/10306826/XR_APILAYER_NOVENDOR_OBSMirror.log)

**Comment by arajkov** [comment]
Ok - dont know what triggered this error but after restarting everything and reconnecting the HMD I didnt get it anymore. OpenXR Toolkit running and Image from iRacing is shown in the OBS Plugin. Will do some more testing and let you know if anything unusual happens :) Thanks again.

[XR_APILAYER_NOVENDOR_OBSMirror.log](https://github.com/Jabbah/OpenXR-Layer-OBSMirror/files/10306906/XR_APILAYER_NOVENDOR_OBSMirror.log)

**Comment by arajkov** [comment]
Lookin good so far ... https://www.twitch.tv/videos/1689954540
