### ISSUE TITLE
Unable to install on Windows 11

### ISSUE THREAD

**Issue by JIAN83157** [Jabbah/OpenXR-Layer-OBSMirror#2]
Another way to install?
Right-clicking and running Install-Layer.ps1 in Windows 11 gives an error

**Comment by Jabbah** [comment]
What is the error?

**Comment by JIAN83157** [comment]
Sorry I can't translate into English here

Jabbah ***@***.***>於 2022年12月26日 週一，下午7:34寫道：

> What is the error?
>

**Comment by JIAN83157** [comment]
I have searched online how to enable windows powershell restrictions.

But should I choose game capture in obs?

Because I still can't see the openxr toolkit window in obs

jian ***@***.***>於 2022年12月26日 週一，下午7:51寫道：

>
> Sorry I can't translate into English here
>
> Jabbah ***@***.***>於 2022年12月26日 週一，下午7:34寫道：
>
>> What is the error?
>>

**Comment by JIAN83157** [comment]
I successfully solved the problem!

works well now

jian ***@***.***>於 2022年12月26日 週一，下午8:02寫道：

> I have searched online how to enable windows powershell restrictions.
>
> But should I choose game capture in obs?
>
> Because I still can't see the openxr toolkit window in obs
>
> jian ***@***.***>於 2022年12月26日 週一，下午7:51寫道：
>
>>
>> Sorry I can't translate into English here
>>
>> Jabbah ***@***.***>於 2022年12月26日 週一，下午7:34寫道：
>>
>>> What is the error?
>>>
