### ISSUE TITLE
Left eye is recorded even if Right Eye is selected

### ISSUE THREAD

**Issue by jaylw314** [Jabbah/OpenXR-Layer-OBSMirror#3]
I attempted to record from the right eye in DCS, since that is where most of the HMD's are displayed by default.  Sure enough, no matter whether "Right Eye" is checked in the plugin properties, the render is always from the left eye.

Unless that's what you meant by "left eye mirror", but it's confusing having the "right eye" option in the properties :)

**Comment by Jabbah** [comment]
Yeah this bit just wasn't finished yet. Should be fixed in v0.2.3 release. Let me know if that is working.

**Comment by jaylw314** [comment]
I tried out 0.2.3 and it seems to select the right eye fine!
