### ISSUE TITLE
Installation causes 'Unknown OpenXR Runtime Error' 

### ISSUE THREAD

**Issue by M0RT75** [Jabbah/OpenXR-Layer-OBSMirror#4]
Installation causes 'Unknown OpenXR Runtime Error' in Open XR Tools, this doesn't seem to affect any VR functionality though:

XrResult failure (XR_ERROR_RUNTIME_FAILURE) 
Origin: xrCreateInstance

![Screenshot 2023-01-01 070310](https://user-images.githubusercontent.com/121745081/210163383-6a8b8ae7-7dc6-41a9-83d3-c269363f70f5.png)
![Screenshot 2023-01-01 070325](https://user-images.githubusercontent.com/121745081/210163385-71fd8cb8-120e-4e39-9075-df74f2256a59.png)

**Comment by Jabbah** [comment]
As per instructions the files need to be installed in your program files dir due to the way WMR works.
