### ISSUE TITLE
Plugin does not record every frame unless OBS is run in administrator mode

### ISSUE THREAD

**Issue by jaylw314** [Jabbah/OpenXR-Layer-OBSMirror#5]
Unless OBS is run in administrator mode, the plugin seems to only record every 3rd frame or so.  When OBS is run in administrator mode, it seems to function as expected

**Comment by Jabbah** [comment]
I think this is expected when recording something like a game that uses high GPU resources:

https://obsproject.com/forum/threads/obs-studio-24-0-3-gpu-priority-fix-testing.111669/

**Comment by jaylw314** [comment]
Thanks, I'll close the issue
