### ISSUE TITLE
How to confirm it's succesfully installed?

### ISSUE THREAD

**Issue by andybak** [Jabbah/OpenXR-Layer-OBSMirror#6]
Does it appear as a new source in OBS? What's it named?

I currently suspect it's not working as I can't see any obvious signs of it in OBS - but then I might be looking in the wrong places.

**Comment by Jabbah** [comment]
It will appear as OpenXR Mirror Capture

<img width="151" alt="image" src="https://user-images.githubusercontent.com/2940221/210622392-0173e54c-bdd5-40e5-a827-7bf7df582aab.png">

You might need to right click on the files you downloaded and unblock them before running the powershell script.

<img width="269" alt="image" src="https://user-images.githubusercontent.com/2940221/210623067-d0169a8e-3e18-4979-8b47-5d493be0eff1.png">

**Comment by andybak** [comment]
Brilliant. It's working now. I'd also misread part of the install instructions so I'm not sure if it was the unblocking that did the trick but it's working.

Maybe mention where to look in the OBS UI to the docs? Might be helpful to others as a sanity check.
